### ISSUE TITLE
Jedi <= 0.17.2 requires parso < 0.8.0

### ISSUE THREAD

**Issue by erykoff** [conda-forge/conda-forge-repodata-patches-feedstock#81]
Issue:
As of today, if you have a fresh environment and install `ipython` (7.17 is current) then you get an incompatible version of `parso` and `jedi`.  This makes the tab-complete not work (which is bad).  I've tracked this down to the fact that the latest version of `parso=0.8.0` (which is in `conda-forge`) requires `jedi>0.17.2` (which is not in `conda-forge`, and in fact 0.17.2 is the latest tagged version of `jedi`).  The problem is that _earlier_ versions of `jedi` did not explicitly put the restriction that they require `parso<0.8.0` (which `0.17.1` and `0.17.2` do).  Therefore, the solver goes and grabs `parso=0.8.0` and then finds that `jedi=0.15.2` is compatible (according to the requirements), but it actually is not.

The solution, I believe, is to patch things so that `jedi<=0.17.2` explicitly require `parso<0.8.0`.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /u1/ki/erykoff/lsst-rh10_20200810/conda/miniconda3-py37_4.8.2/envs/ipy717-3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
ipython                   7.17.0           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.2                   py38_0    conda-forge
ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_14    conda-forge
libgfortran-ng            7.5.0               hdf63c60_14    conda-forge
libgomp                   9.3.0               h24d8f2e_14    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_14    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
numpy                     1.19.1           py38h8854b6b_0    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
parso                     0.8.0              pyh9f0ad1d_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pip                       20.2.2                     py_0    conda-forge
prompt-toolkit            3.0.6                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.6.1                      py_0    conda-forge
python                    3.8.5           h4d41432_2_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               h4cf870e_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1007    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : ipy717-3
    active env location : /u1/ki/erykoff/lsst-rh10_20200810/conda/miniconda3-py37_4.8.2/envs/ipy717-3
            shell level : 2
       user config file : /afs/slac.stanford.edu/u/ki/erykoff/.condarc
 populated config files : /afs/slac.stanford.edu/u/ki/erykoff/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=8.0
                          __glibc=2.12
       base environment : /u1/ki/erykoff/lsst-rh10_20200810/conda/miniconda3-py37_4.8.2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /u1/ki/erykoff/lsst-rh10_20200810/conda/miniconda3-py37_4.8.2/pkgs
                          /afs/slac.stanford.edu/u/ki/erykoff/.conda/pkgs
       envs directories : /u1/ki/erykoff/lsst-rh10_20200810/conda/miniconda3-py37_4.8.2/envs
                          /afs/slac.stanford.edu/u/ki/erykoff/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/2.6.32-754.27.1.el6.x86_64 rhel/6.10 glibc/2.12
                UID:GID : 10646:1092
             netrc file : /afs/slac.stanford.edu/u/ki/erykoff/.netrc
           offline mode : False
```
</details>

**Comment by beckermr** [comment]
PRs welcome!

**Comment by beckermr** [comment]
@conda-forge/jedi @conda-forge/parso Can you all comment on this?

**Comment by nehaljwani** [comment]
I redirected OP to this repo. Original request was at https://github.com/conda-forge/jedi-feedstock/issues/34

**Comment by beckermr** [comment]
mmk - is the requested change in the dependencies correct?

**Comment by nehaljwani** [comment]
I have verified that this is indeed an issue and all old versions of jedi with loose dependency on parso are affected by it. This has also been reported upstream at https://github.com/davidhalter/jedi/issues/1654

Unfortunately, parso makes breaking changes in minor releases.

We can wait for parso-0.8.0 compatible jedi 0.18.0 to be released. But then the problem will occur again with the next minor of parso. So I think OP is right and we should hotfix old versions of jedi with loose dep on parso to the corresponding next minors.

**Comment by beckermr** [comment]
OK. Can the devs of @conda-forge/jedi @conda-forge/parso please send a PR here to patch the data then?

**Comment by asmeurer** [comment]
You might need information from @davidhalter on which parso versions should be pinned for older jedi versions.

**Comment by erykoff** [comment]
From https://github.com/davidhalter/parso/issues/148#issuecomment-673977148 I can infer that each version of jedi that specifies a minimum parso version should also specify a max that is less than the next minor version of parso?

**Comment by davidhalter** [comment]
> Unfortunately, parso makes breaking changes in minor releases.

This is not a minor release. This is a pre-1.0 release and according to semantic versioning it's totally fine to break the API at that point. The API is not yet considered stable.

https://semver.org/

> We can wait for parso-0.8.0 compatible jedi 0.18.0 to be released. But then the problem will occur again with the next minor of parso. So I think OP is right and we should hotfix old versions of jedi with loose dep on parso to the corresponding next minors.

I don't think that is the actual issue. The dependency resolver for conda does the wrong thing: It picks an older Jedi version when there is no reason to do that. That should be fixed and that is most likely an issue with conda. This does not happen with pip.

> You might need information from @davidhalter on which parso versions should be pinned for older jedi versions.

I have unfortunately no idea which versions are compatible. I wanted to pin the parso versions a long time ago, but some people were unhappy, because back then the pip dependency resolver was even worse. I only started pinning recently.

------

P.S.: I also don't think there's any reason to use an older Jedi version, they are just worse and buggier.

**Comment by davidhalter** [comment]
I just want to point out that this is not really a fix of the actual problem.

It's probably also an incorrect assumption that Jedi 0.15.2 should be used with parso < 0.7.x.

**Comment by rhuffy** [comment]
This issue is still occurring when resolving an environment for Python 2. Jedi 0.17.x is not built for Python 2, so conda picks Jedi 0.16.0, and because that version does not pin Parso, and versions of Parso 0.8.0 were published that did not require Python >=3.6, conda picks Parso 0.8.0. Opened an issue here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/81

**Comment by davidhalter** [comment]
> Jedi 0.17.x is not built for Python 2, so conda picks Jedi 0.16.0

This is not true. 0.17.x works fine with Python 2.

**Comment by rhuffy** [comment]
Yes, the issue is not with Jedi, but with conda-forge. Jedi on conda-forge has different tarballs for each minor version of Python. Prior to today, there was not a tarball for Jedi 0.17.x - python 2.7 - the most recent was 0.16.0, which didn't pin parso <0.8.0, causing an issue for my python 2 conda environments.

However, this was just resolved here: https://github.com/conda-forge/jedi-feedstock/issues/36

**Comment by jakirkham** [comment]
Well I think the important thing that is not getting surfaced in this discussion is Python 2 was intentionally dropped by conda-forge earlier this year ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/491 ). This is aligned with larger community efforts where Python 2 has been dropped ( https://www.python.org/doc/sunset-python-2/ ) ( https://python3statement.org ).

While it's certainly great that the issue in this case was resolvable. It's important to be aware that there is no maintenance effort in conda-forge going towards Python 2. So one can reasonably expect environments on Python 2 to lag both in terms of package versions and fixes.

cc @conda-forge/core (for vis)
